//Usuario
export const USUARIO_LOGIN = "USUARIO_LOGIN";
export const USUARIO_CERRAR_SESION = "USUARIO_CERRAR_SESION";

//Alertas
export const ALERTA_SHOW = "ALERTA_SHOW";
export const ALERTA_HIDE = "ALERTA_HIDE";

//MAIN CONTENT
export const MAIN_CONTENT_CARGANDO = "MAIN_CONTENT_CARGANDO";
export const SET_TIPO_TRIBUTOS = "SET_TIPO_TRIBUTOS";
export const SET_TIPO_CEDULONES = "SET_TIPO_CEDULONES";
export const SET_ESTADO_PAGOS = "SET_ESTADO_PAGOS";
export const SET_PUBLIC_KEY_MERCADO_PAGO = "SET_PUBLIC_KEY_MERCADO_PAGO";
export const PARA_MOBILE = "PARA_MOBILE";
export const SET_APLICACION_PANEL = "SET_APLICACION_PANEL";