//Usuario
export const USUARIO_LOGIN = "USUARIO_LOGIN";
export const USUARIO_CERRAR_SESION = "USUARIO_CERRAR_SESION";

//Alertas
export const ALERTA_SHOW = "ALERTA_SHOW";
export const ALERTA_HIDE = "ALERTA_HIDE";

//MAIN CONTENT
export const MAIN_CONTENT_CARGANDO = "MAIN_CONTENT_CARGANDO";
