import DetalleTributo from "@UI/Paginas/TributarioOnline/DetalleTributario/Detalle/index";
import TributarioOnline from "@UI/Paginas/TributarioOnline/index";

const Menu = [
  {
    url: "/DetalleTributario/:tributo/:identificador",
    exact: true,
    mostrarEnMenu: false,
    component: DetalleTributo,
    nombre: "Automotor",
    titulo: "Automotor",
  },
  {
    url: "/Inicio",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Inicio",
    titulo: "Inicio",
  },
  {
    url: "/Inicio/Tributo/Automotor",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Automotor",
    titulo: "Automotor",
  },
  {
    url: "/Inicio/Tributo/Inmueble",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Inmueble",
    titulo: "Inmueble",
  },
  {
    url: "/Inicio/Tributo/Comercio",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Comercios e Industria",
    titulo: "Comercios e Industria",
  },
  {
    url: "/Inicio/Tributo/Cementerio",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Cementerio",
    titulo: "Cementerio",
  },
  {
    url: "/Inicio/Tributo/FeriaMercado",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Ferias y Mercados",
    titulo: "Ferias y Mercados",
  },
  {
    url: "/Inicio/Tributo/TaxiRemis",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Taxis/Remises",
    titulo: "Taxis/Remises",
  },
  {
    url: "/Inicio/Tributo/Tributos",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Agentes de percepción y retención",
    titulo: "Agentes de percepción y retención",
  },
  {
    url: "/Inicio/Tributo/Tributos",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Contribución por mejoras",
    titulo: "Contribución por mejoras",
  },
  {
    url: "/Inicio/Tributo/Tributos",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Planes de Vivienda",
    titulo: "Planes de Vivienda",
  },
  {
    url: "/Inicio/Tributo/Tributos",
    exact: true,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Consulta por número de nexo",
    titulo: "Consulta por número de nexo",
  },
  {
    url: "/Inicio",
    exact: false,
    mostrarEnMenu: true,
    component: TributarioOnline,
    nombre: "Volver",
    titulo: "Volver",
  }
];

export default Menu;