//Consumo WebService
export const GET_INFO_CONTRIBUCION = "GET_INFO_CONTRIBUCION";
export const GET_INFO_MULTAS = "GET_INFO_MULTAS";
export const GET_INFO_JUICIOS_CONTR = "GET_INFO_JUICIOS_CONTR";
export const GET_INFO_JUICIOS_MULTAS = "GET_INFO_JUICIOS_MULTAS";
export const GET_INFO_PLANES_PAGO = "GET_INFO_PLANES_PAGO";
export const GET_INFO_ULTIMOS_PAGOS = "GET_INFO_ULTIMOS_PAGOS";
export const GET_INFORME_ANTECEDENTES = "GET_INFORME_ANTECEDENTES";
export const GET_INFORME_REMAT = "GET_INFORME_REMAT";
export const GET_INFORME_CUENTA = "GET_INFORME_CUENTA";
export const GET_REPORTE_INFORME_CUENTA = "GET_REPORTE_INFORME_CUENTA";
export const SET_PAGOS_MERCADO_PAGO = "SET_PAGOS_MERCADO_PAGO";
export const RESET_INFO_DETALLE_TRIBUTO = "RESET_INFO_DETALLE_TRIBUTO";
export const GET_REPORTE_INFORME_REMAT = "GET_REPORTE_INFORME_REMAT";
export const GET_REPORTE_INFORME_ANTECEDENTES = "GET_REPORTE_INFORME_ANTECEDENTES";