//Consumo WebService
export const GET_INFO_CONTRIBUCION = "GET_INFO_CONTRIBUCION";
export const GET_INFO_MULTAS = "GET_INFO_MULTAS";
export const GET_INFO_JUICIOS_CONTR = "GET_INFO_JUICIOS_CONTR";
export const GET_INFO_JUICIOS_MULTAS = "GET_INFO_JUICIOS_MULTAS";
export const GET_INFO_PLANES_PAGO = "GET_INFO_PLANES_PAGO";
export const GET_INFO_ULTIMOS_PAGOS = "GET_INFO_ULTIMOS_PAGOS";