//Consumo WebService
export const GET_TRIBUTOS_CUIT = "GET_TRIBUTOS_CUIT";
export const GET_SOLICITUDES_PERMISOS = "GET_SOLICITUDES_PERMISOS";
export const CANCELAR_SOLICITUD_PERMISOS = "CANCELAR_SOLICITUD_PERMISOS";