//Consumo WebService
export const GET_TRIBUTOS_CUIT = "GET_TRIBUTOS_CUIT";
export const GET_SOLICITUDES_PERMISOS = "GET_SOLICITUDES_PERMISOS";
export const GET_MIS_REPRESENTANTES = "GET_MIS_REPRESENTANTES";
export const GET_MIS_REPRESENTADOS = "GET_MIS_REPRESENTADOS";
export const CANCELAR_SOLICITUD_PERMISOS = "CANCELAR_SOLICITUD_PERMISOS";

export const CAMBIAR_ESTADO_PERMISO = "CAMBIAR_ESTADO_PERMISO";
export const AGREGAR_REPRESENTADO_GRILLA = "AGREGAR_REPRESENTADO_GRILLA";